# -*- coding: utf-8 -*-
"""Copy of Template Submission Akhir.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNotsmMuwGWN1t9lsovJBHAzDASXRaoD

# Proyek Klasifikasi Gambar: [Input Nama Dataset]
- **Nama:** [Input Nama]
- **Email:** [Input Email]
- **ID Dicoding:** [Input Username]

## Import Semua Packages/Library yang Digunakan
"""

!pip install -q tensorflowjs
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Library yang sering digunakan
import os, shutil
import zipfile
import random
from random import sample
import shutil
from shutil import copyfile
import pathlib
from pathlib import Path
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm as tq
import subprocess
from google.colab import files

# Commented out IPython magic to ensure Python compatibility.
# Mengimpor libraries untuk visualisasi
# %matplotlib inline
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.image import imread

# Mengimpor libraries untuk pemrosesan data gambar
import cv2
from PIL import Image
import skimage
from skimage import io
from skimage.transform import resize
from skimage.transform import rotate, AffineTransform, warp
from skimage import img_as_ubyte
from skimage.exposure import adjust_gamma
from skimage.util import random_noise

# Mengimpor libraries untuk pembuatan dan evaluasi model
import keras
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
import tensorflow as tf
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models, callbacks
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.callbacks import ModelCheckpoint, Callback, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Sequential
import tensorflowjs as tfjs

"""## Data Preparation

### Data Loading
"""

zip_path = '/content/dataset_cat_dog.zip'
extract_dir = '/content/dataset'

# Ekstrak zip
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print("Dataset berhasil diekstrak ke:", extract_dir)
print("Isi folder dataset:", os.listdir(extract_dir))

def create_validation_split(test_dir, val_dir, split_ratio=0.2):
    os.makedirs(val_dir, exist_ok=True)
    for category in os.listdir(test_dir):
        test_cat_dir = os.path.join(test_dir, category)
        val_cat_dir = os.path.join(val_dir, category)
        os.makedirs(val_cat_dir, exist_ok=True)

        files = os.listdir(test_cat_dir)
        random.shuffle(files)
        n_val = int(len(files) * split_ratio)
        val_files = files[:n_val]

        for f in val_files:
            shutil.move(os.path.join(test_cat_dir, f),
                        os.path.join(val_cat_dir, f))

"""### Data Preprocessing

#### Split Dataset
"""

val_dir = "/content/dataset/Val"
test_dir = "/content/dataset/Test"

create_validation_split(test_dir, val_dir, split_ratio=0.2)
train_dir = '/content/dataset/Train'

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    shear_range=0.2,
    horizontal_flip=True
)

val_test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(150, 150),
    batch_size=64,
    class_mode='binary'
)

val_generator = val_test_datagen.flow_from_directory(
    val_dir,
    target_size=(150, 150),
    batch_size=64,
    class_mode='binary'
)

test_generator = val_test_datagen.flow_from_directory(
    test_dir,
    target_size=(150, 150),
    batch_size=64,
    class_mode='binary'
)

"""## Modelling"""

# Transfer learning backbone
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(150,150,3))
base_model.trainable = False  # Freeze base model

# Bangun Sequential model
model = Sequential([
    base_model,
    Conv2D(64, (3,3), activation='relu', padding='same'),
    MaxPooling2D(2,2),
    Conv2D(32, (3,3), activation='relu', padding='same'),
    MaxPooling2D(2,2),
    GlobalAveragePooling2D(),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.summary()

callbacks = [
    EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True),
    ModelCheckpoint('best_model.h5', monitor='val_accuracy', save_best_only=True)
]
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=20,
    callbacks=callbacks
)
loss, acc = model.evaluate(test_generator)
print(f"\n Akurasi pada data test: {acc * 100:.2f}%")

"""## Evaluasi dan Visualisasi"""

# Evaluasi model pada data train, validation, dan test
train_loss, train_acc = model.evaluate(train_generator, verbose=0)
val_loss, val_acc = model.evaluate(val_generator, verbose=0)
test_loss, test_acc = model.evaluate(test_generator, verbose=0)

print("Hasil Evaluasi Model:")
print(f"Train Accuracy      : {train_acc*100:.2f}%")
print(f"Validation Accuracy : {val_acc*100:.2f}%")
print(f"Test Accuracy       : {test_acc*100:.2f}%")

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(len(acc))

plt.plot(epochs, acc, 'r')
plt.plot(epochs, val_acc, 'b')
plt.title('Training and Validation Accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

plt.plot(epochs, loss, 'r')
plt.plot(epochs, val_loss, 'b')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.title('Training and Validaion Loss')
plt.show()

"""## Konversi Model"""

# ===== Simpan model dalam format Keras =====
model.save("mobilenetv2_seq_catdog.keras")

# ===== Simpan model dalam format SavedModel =====
model.export("mobilenetv2_seq_catdog_savedmodel")

# ===== Konversi ke TFLite =====
converter = tf.lite.TFLiteConverter.from_saved_model("mobilenetv2_seq_catdog_savedmodel")
tflite_model = converter.convert()
with open("mobilenetv2_seq_catdog.tflite", "wb") as f:
    f.write(tflite_model)

!tensorflowjs_converter --input_format=tf_saved_model mobilenetv2_seq_catdog_savedmodel mobilenetv2_seq_catdog_tfjs

shutil.make_archive('mobilenetv2_seq_catdog_savedmodel', 'zip', 'mobilenetv2_seq_catdog_savedmodel')

shutil.make_archive('mobilenetv2_seq_catdog_tfjs', 'zip', 'mobilenetv2_seq_catdog_tfjs')

files.download('mobilenetv2_seq_catdog_savedmodel.zip')
files.download('mobilenetv2_seq_catdog_tfjs.zip')

"""## Inference (Optional)"""

model_path = "/content/mobilenetv2_seq_catdog_savedmodel"
model = tf.keras.layers.TFSMLayer(model_path, call_endpoint='serving_default')

img_path = "gambar_kucing.jpg"
img = image.load_img(img_path, target_size=(150, 150))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0) / 255.0

output = model(img_array)
print(output)

predictions = list(output.values())[0].numpy()

confidence = float(np.max(predictions))
class_index = int(np.argmax(predictions))
classes = ["Cat", "Dog"]
print(f"Prediction: {classes[class_index]} {confidence*100:.2f}%")

"""# **Membuat File Requirment**"""

pip freeze > requirements.txt